// app/components/name-checker/DomainAvailabilityMatrix.vue
<template>
  <UCard class="h-fit" :ui="{ body: '!p-6' }">
    <template #header>
      <div class="flex items-center gap-2">
        <UIcon name="i-heroicons-globe-alt" class="text-lg" />
        <h3 class="text-lg font-semibold">Domain Availability</h3>
      </div>
    </template>
    
    <div v-if="hasResults" class="overflow-x-auto">
      <table class="w-full text-sm">
        <thead>
          <tr class="border-b border-neutral-200 dark:border-neutral-700">
            <th class="text-left p-2 font-semibold text-neutral-600 dark:text-neutral-400">Name</th>
            <th v-for="tld in tlds" :key="tld" class="text-center p-1 font-semibold text-neutral-600 dark:text-neutral-400 min-w-[3rem]">
              .{{ tld }}
            </th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="variation in nameVariations" :key="variation" 
              class="border-b border-neutral-100 dark:border-neutral-800 hover:bg-neutral-50 dark:hover:bg-neutral-800">
            <td class="p-2 font-mono text-neutral-700 dark:text-neutral-300 font-medium">
              {{ variation }}
            </td>
            <td v-for="tld in tlds" :key="tld" class="text-center p-1">
              <UTooltip :text="getDomainTooltipText(variation, tld)">
                <UButton
                  :to="getDomainUrl(variation, tld)"
                  target="_blank"
                  variant="ghost"
                  size="xs"
                  class="p-1"
                >
                  <UIcon 
                    :name="getDomainStatusIcon(variation, tld)" 
                    :class="getDomainStatusColor(variation, tld)" 
                    class="text-lg"
                  />
                </UButton>
              </UTooltip>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    
    <div v-else-if="hasError && !isLoading" class="text-center py-8">
      <UIcon name="i-heroicons-exclamation-triangle" class="text-yellow-500 text-2xl mb-2" />
      <p class="text-sm text-neutral-600 dark:text-neutral-400">Failed to check domain availability</p>
      <UButton @click="$emit('retry')" variant="ghost" size="xs" class="mt-2">
        Retry
      </UButton>
    </div>
    
    <div v-else-if="isLoading" class="overflow-x-auto">
      <table class="w-full text-sm">
        <thead>
          <tr class="border-b border-neutral-200 dark:border-neutral-700">
            <th class="text-left p-2 font-semibold text-neutral-600 dark:text-neutral-400 min-w-[4rem]">
              <USkeleton class="h-4 w-16" />
            </th>
            <th v-for="tld in tlds" :key="tld" class="text-center p-1 font-semibold text-neutral-600 dark:text-neutral-400 min-w-[3rem]">
              <USkeleton class="h-4 w-8 mx-auto" />
            </th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="variation in nameVariations" :key="variation" class="border-b border-neutral-100 dark:border-neutral-800">
            <td class="p-2">
              <USkeleton class="h-4 w-20" />
            </td>
            <td v-for="tld in tlds" :key="tld" class="text-center p-1">
              <!-- Show progressive results if available -->
              <template v-if="getDomainResult(variation, tld)">
                <UTooltip :text="getDomainTooltipText(variation, tld)">
                  <UButton
                    :to="getDomainUrl(variation, tld)"
                    target="_blank"
                    variant="ghost"
                    size="xs"
                    class="p-1"
                  >
                    <UIcon 
                      :name="getDomainStatusIcon(variation, tld)" 
                      :class="getDomainStatusColor(variation, tld)" 
                      class="text-lg"
                    />
                  </UButton>
                </UTooltip>
              </template>
              <template v-else>
                <USkeleton class="size-6 mx-auto" :ui="{ rounded: 'rounded-full' }" />
              </template>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    
    <div v-else class="overflow-x-auto">
      <table class="w-full text-sm">
        <thead>
          <tr class="border-b border-neutral-200 dark:border-neutral-700">
            <th class="text-left p-2 font-semibold text-neutral-600 dark:text-neutral-400">Name</th>
            <th v-for="tld in tlds" :key="tld" class="text-center p-1 font-semibold text-neutral-600 dark:text-neutral-400 min-w-[3rem]">
              .{{ tld }}
            </th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="variation in nameVariations" :key="variation" 
              class="border-b border-neutral-100 dark:border-neutral-800">
            <td class="p-2 font-mono text-neutral-500 dark:text-neutral-400 font-medium">
              {{ variation }}
            </td>
            <td v-for="tld in tlds" :key="tld" class="text-center p-1">
              <div class="p-1">
                <UIcon 
                  name="i-heroicons-question-mark-circle" 
                  class="text-lg text-neutral-300 dark:text-neutral-600"
                />
              </div>
            </td>
          </tr>
        </tbody>
      </table>
      <div class="text-center mt-4 text-neutral-500 dark:text-neutral-400">
        <p class="text-sm">Enter a name above to check domain availability</p>
      </div>
    </div>
  </UCard>
</template>

<script setup lang="ts">
interface DomainResult {
  url: string
  variation: string
  tld: string
  available: boolean
  priceInCents: number
  status: 'success' | 'error'
  expires?: string
  error?: string
}

const props = defineProps<{
  domainResults: Map<string, DomainResult>
  isLoading: boolean
  searchName: string
}>()

defineEmits<{
  retry: []
}>()

// Computed status for UI
const hasResults = computed(() => props.domainResults.size > 0)
const hasError = computed(() => 
  Array.from(props.domainResults.values()).some(result => result.status === 'error')
)

// Domain matrix helpers
const tlds = ['com', 'net', 'org', 'io', 'dev', 'app', 'in', 'tech', 'co', 'ai', 'xyz', 'me', 'ing']

const nameVariations = computed(() => {
  // Always show dash placeholders for name variations
  return ['-', 'get-', 'try-', '-app', '-ly']
})

const getDomainUrl = (variation: string, tld: string) => {
  if (!props.searchName) return `https://${variation}.${tld}`
  
  // Replace dash with actual search name
  const actualVariation = variation.replace('-', props.searchName)
  return `https://${actualVariation}.${tld}`
}

// Domain-specific helper functions
const getDomainResult = (variation: string, tld: string) => {
  const key = `${variation}-${tld}`
  return props.domainResults.get(key)
}

const getDomainStatusIcon = (variation: string, tld: string) => {
  const result = getDomainResult(variation, tld)
  if (!result) return 'i-heroicons-question-mark-circle'
  
  if (result.status === 'error') return 'i-heroicons-exclamation-triangle'
  return result.available ? 'i-heroicons-check-circle' : 'i-heroicons-x-circle'
}

const getDomainStatusColor = (variation: string, tld: string) => {
  const result = getDomainResult(variation, tld)
  if (!result) return 'text-neutral-400 dark:text-neutral-500'
  
  if (result.status === 'error') return 'text-yellow-500 dark:text-yellow-400'
  return result.available ? 'text-green-500 dark:text-green-400' : 'text-red-500 dark:text-red-400'
}

const getDomainTooltipText = (variation: string, tld: string) => {
  const result = getDomainResult(variation, tld)
  if (!result) return getDomainUrl(variation, tld)
  
  if (result.status === 'error') {
    return result.error || 'Error checking domain'
  }
  
  if (!result.available && result.expires) {
    const expiryDate = new Date(result.expires)
    const localExpiry = expiryDate.toLocaleDateString(undefined, {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    })
    return `Expires: ${localExpiry}`
  }
  
  return result.available ? 'Available' : 'Not available'
}
</script>

// src/components/tools/name-checker/DomainAvailabilityMatrix.tsx
import { Card, Button, Spinner, Table } from '@heroui/react'
import { TLDS, NAME_VARIATIONS, type DomainResult, type NameVariation, type TLD } from './types'
import IconCheck from '~icons/tabler/circle-check'
import IconX from '~icons/tabler/circle-x'
import IconQuestion from '~icons/tabler/circle-dashed'
import IconWarning from '~icons/tabler/alert-triangle'

interface Props {
  domainResults: Map<string, DomainResult>
  isLoading: boolean
  searchName: string
  onRetry: () => void
}

export default function DomainAvailabilityMatrix({ domainResults, isLoading, searchName, onRetry }: Props) {
  const hasResults = domainResults.size > 0
  const hasError = Array.from(domainResults.values()).some((result) => result.status === 'error')

  const getDomainResult = (variation: NameVariation, tld: TLD) =>
    domainResults.get(`${variation}-${tld}`)

  const getDomainUrl = (variation: NameVariation, tld: TLD) => {
    if (!searchName) return `https://${variation}.${tld}`
    return `https://${variation.replace('-', searchName)}.${tld}`
  }

  const getTooltipText = (variation: NameVariation, tld: TLD) => {
    const result = getDomainResult(variation, tld)
    if (!result) return getDomainUrl(variation, tld)
    if (result.status === 'error') return result.error || 'Error checking domain'
    if (!result.available && result.expires) {
      const localExpiry = new Date(result.expires).toLocaleDateString(undefined, {
        year: 'numeric',
        month: 'short',
        day: 'numeric',
      })
      return `Expires: ${localExpiry}`
    }
    return result.available ? 'Available' : 'Not available'
  }

  const getCellContent = (variation: NameVariation, tld: TLD) => {
    const result = getDomainResult(variation, tld)
    const isLoadingCell = isLoading && !result

    if (isLoadingCell) return <Spinner size="sm" />
    if (!result) return <IconQuestion className="text-lg text-muted" />
    if (result.status === 'error') return <IconWarning className="text-lg text-yellow-500 dark:text-yellow-400" />
    return result.available
      ? <IconCheck className="text-lg text-green-500 dark:text-green-400" />
      : <IconX className="text-lg text-red-500 dark:text-red-400" />
  }

  return (
    <Card.Root variant="default">
      <Card.Header>
        <Card.Title>Domain Availability</Card.Title>
      </Card.Header>
      <Card.Content className="p-0">
        {hasError && !isLoading && !hasResults ? (
          <div className="text-center py-8 px-4">
            <IconWarning className="text-yellow-500 text-2xl mx-auto mb-2" />
            <p className="text-sm text-muted">Failed to check domain availability</p>
            <Button variant="ghost" onPress={onRetry} className="mt-2 text-sm">
              Retry
            </Button>
          </div>
        ) : !hasResults && !isLoading && !hasError ? (
          <div className="text-center py-8 px-4 text-muted">
            <p className="text-sm">Enter a name above to check domain availability</p>
          </div>
        ) : (
          <Table>
            <Table.ScrollContainer className="overflow-x-auto">
              <Table.Content>
                <Table.Header>
                  <Table.Column className="text-left">Name</Table.Column>
                  {TLDS.map((tld) => (
                    <Table.Column key={tld} className="text-center">.{tld}</Table.Column>
                  ))}
                </Table.Header>
                <Table.Body>
                  {NAME_VARIATIONS.map((variation) => (
                    <Table.Row key={variation}>
                      <Table.Cell>
                        <span className="font-mono text-muted text-sm">{variation}</span>
                      </Table.Cell>
                      {TLDS.map((tld) => (
                        <Table.Cell key={`${variation}-${tld}`} className="text-center">
                          <a
                            href={getDomainUrl(variation, tld)}
                            target="_blank"
                            rel="noopener noreferrer"
                            title={getTooltipText(variation, tld)}
                            className="inline-flex items-center justify-center p-1 rounded hover:bg-default transition-colors"
                          >
                            {getCellContent(variation, tld)}
                          </a>
                        </Table.Cell>
                      ))}
                    </Table.Row>
                  ))}
                </Table.Body>
              </Table.Content>
            </Table.ScrollContainer>
          </Table>
        )}
      </Card.Content>
    </Card.Root>
  )
}
