// app/pages/tools/name-checker.vue
<script setup lang="ts">
import { useDebounceFn, useUrlSearchParams } from '@vueuse/core'
import PlatformAvailabilityCard from '~/components/name-checker/PlatformAvailabilityCard.vue'
import DomainAvailabilityMatrix from '~/components/name-checker/DomainAvailabilityMatrix.vue'

definePageMeta({
  layout: false,
})

// Types for new API structure
interface PlatformResult {
  platform: string
  available: boolean
  link: string
  status: 'success' | 'error'
}

interface DomainResult {
  url: string
  variation: string
  tld: string
  available: boolean
  priceInCents: number
  status: 'success' | 'error'
}

const searchParams = useUrlSearchParams('history', {
  initialValue: {
    name: '',
  }
})

// Platform and domain configuration
const platforms = [
  'GitHub repo', 'GitHub org/user', 'PyPI package', 'Homebrew cask/formula', 'Rust crate',
  'npm package', 'npm org', 'Ruby gem', 'Nuget package', 'Packagist package', 'Go package'
]

const tlds = ['com', 'net', 'org', 'io', 'dev', 'app', 'in', 'tech', 'co', 'ai', 'xyz', 'me', 'ing']
const variations = ['-', 'get-', 'try-', '-app', '-ly']

// Reactive state
const platformResults = ref<Map<string, PlatformResult>>(new Map())
const domainResults = ref<Map<string, DomainResult>>(new Map())
const isLoading = ref(false)
const error = ref('')
const currentAbortController = ref<AbortController | null>(null)

async function checkPlatforms(name: string, signal: AbortSignal) {
  const promises = platforms.map(async (platform) => {
    try {
      const result = await $fetch('/api/check-platform', {
        query: { name, platform },
        signal
      }) as PlatformResult
      
      // Only update if not aborted
      if (!signal.aborted) {
        platformResults.value.set(platform, result)
      }
    } catch (err: any) {
      // Don't show errors for aborted requests
      if (err.name === 'AbortError' || signal.aborted) {
        return
      }
      
      platformResults.value.set(platform, {
        platform,
        available: false,
        link: '#',
        status: 'error'
      })
    }
  })

  return Promise.allSettled(promises)
}

async function checkDomains(name: string, signal: AbortSignal) {
  const promises = []
  
  for (const tld of tlds) {
    for (const variation of variations) {
      promises.push(async () => {
        const key = `${variation}-${tld}`
        try {
          const result = await $fetch('/api/check-domain', {
            query: { name, variation, tld },
            signal
          }) as DomainResult
          
          // Only update if not aborted
          if (!signal.aborted) {
            domainResults.value.set(key, result)
          }
        } catch (err: any) {
          // Don't show errors for aborted requests
          if (err.name === 'AbortError' || signal.aborted) {
            return
          }
          
          domainResults.value.set(key, {
            url: `https://${variation.replace('-', name)}.${tld}`,
            variation,
            tld,
            available: false,
            priceInCents: 0,
            status: 'error'
          })
        }
      })
    }
  }

  return Promise.allSettled(promises.map(fn => fn()))
}

async function doSearch() {
  if (!searchParams.name.trim()) {
    error.value = 'Please enter a name'
    return
  }

  // Cancel any ongoing requests
  if (currentAbortController.value) {
    currentAbortController.value.abort()
  }

  // Create new abort controller for this search
  currentAbortController.value = new AbortController()
  const signal = currentAbortController.value.signal

  error.value = ''
  isLoading.value = true
  
  // Clear previous results
  platformResults.value.clear()
  domainResults.value.clear()

  try {
    await Promise.all([
      checkPlatforms(searchParams.name, signal),
      checkDomains(searchParams.name, signal)
    ])
  } catch (err: any) {
    // Don't show errors for aborted requests
    if (err.name !== 'AbortError' && !signal.aborted) {
      error.value = 'Search failed. Please try again.'
    }
  } finally {
    // Only update loading state if this request wasn't aborted
    if (!signal.aborted) {
      isLoading.value = false
    }
  }
}

const debouncedSearch = useDebounceFn(() => {
  if (searchParams.name.trim()) {
    doSearch()
  }
}, 500)

watch(() => searchParams.name, debouncedSearch)

// Cleanup on unmount
onUnmounted(() => {
  if (currentAbortController.value) {
    currentAbortController.value.abort()
  }
})

</script>

<template>
  <NuxtLayout name="tool-layout" emoji="™️" toolName="Name Checker">
    <div class="h-[calc(100vh-theme(spacing.12))] p-6 grid grid-rows-[auto_1fr] gap-6">
      <!-- Header Section -->
      <div class="text-center">
        <h1 class="text-3xl font-bold text-slate-900 dark:text-white mb-2">Name Checker</h1>
        <p class="text-slate-600 dark:text-slate-400 mb-6">Find out if your project name is taken across platforms and domains</p>
        
        <div class="max-w-md mx-auto">
          <UInput 
            v-model.trim="searchParams.name" 
            @keyup.enter="doSearch" 
            placeholder="Enter project name..." 
            size="lg"
            :loading="isLoading"
            class="w-full"
          />
          
          <UAlert 
            v-if="error" 
            icon="i-heroicons-exclamation-circle" 
            color="error" 
            variant="subtle" 
            :description="error" 
            class="mt-3"
          />
        </div>
      </div>

      <!-- Results Section -->
      <div v-if="searchParams.name.trim()" class="space-y-6">
        
        <DomainAvailabilityMatrix
          :domain-results="domainResults"
          :is-loading="isLoading"
          :search-name="searchParams.name"
          @retry="doSearch"
        />

        <PlatformAvailabilityCard
          :platform-results="platformResults"
          :is-loading="isLoading"
          @retry="doSearch"
        />
      </div>
      
      <!-- Empty State -->
      <div v-else class="flex items-center justify-center h-full">
        <div class="text-center">
          <UIcon name="i-heroicons-magnifying-glass" class="text-4xl text-neutral-400 mb-4" />
          <p class="text-neutral-500 dark:text-neutral-400">Enter a name above to check availability</p>
        </div>
      </div>
    </div>
  </NuxtLayout>
</template>

// src/components/tools/name-checker/index.tsx
import { useEffect, useRef, useState, useCallback } from 'react'
import { NuqsAdapter } from 'nuqs/adapters/react'
import { parseAsString, useQueryState } from 'nuqs'
import { SearchField, Alert } from '@heroui/react'
import { PLATFORMS, TLDS, NAME_VARIATIONS, type PlatformResult, type DomainResult } from './types'
import PlatformAvailabilityCard from './PlatformAvailabilityCard'
import DomainAvailabilityMatrix from './DomainAvailabilityMatrix'
import IconSearch from '~icons/tabler/search'

function NameCheckerContent() {
  const [searchName, setSearchName] = useQueryState(
    'name',
    parseAsString.withDefault('').withOptions({ shallow: false })
  )

  const [platformResults, setPlatformResults] = useState<Map<string, PlatformResult>>(new Map())
  const [domainResults, setDomainResults] = useState<Map<string, DomainResult>>(new Map())
  const [isLoading, setIsLoading] = useState(false)
  const [error, setError] = useState('')
  const currentAbortController = useRef<AbortController | null>(null)
  const debounceTimer = useRef<ReturnType<typeof setTimeout> | null>(null)

  const checkPlatforms = useCallback(async (name: string, signal: AbortSignal) => {
    const promises = PLATFORMS.map(async (platform) => {
      try {
        const response = await fetch(`/api/check-platform?name=${encodeURIComponent(name)}&platform=${encodeURIComponent(platform)}`, {
          signal,
        })
        const result = (await response.json()) as PlatformResult

        if (!signal.aborted) {
          setPlatformResults((prev) => new Map(prev).set(platform, result))
        }
      } catch (err: any) {
        if (err.name === 'AbortError' || signal.aborted) return

        setPlatformResults((prev) =>
          new Map(prev).set(platform, {
            platform,
            available: false,
            link: '#',
            status: 'error',
          })
        )
      }
    })

    return Promise.allSettled(promises)
  }, [])

  const checkDomains = useCallback(async (name: string, signal: AbortSignal) => {
    const promises: Promise<void>[] = []

    for (const tld of TLDS) {
      for (const variation of NAME_VARIATIONS) {
        const key = `${variation}-${tld}`
        promises.push(
          (async () => {
            try {
              const response = await fetch(
                `/api/check-domain?name=${encodeURIComponent(name)}&variation=${encodeURIComponent(variation)}&tld=${encodeURIComponent(tld)}`,
                { signal }
              )
              const result = (await response.json()) as DomainResult

              if (!signal.aborted) {
                setDomainResults((prev) => new Map(prev).set(key, result))
              }
            } catch (err: any) {
              if (err.name === 'AbortError' || signal.aborted) return

              const actualVariation = variation.replace('-', name)
              setDomainResults((prev) =>
                new Map(prev).set(key, {
                  url: `https://${actualVariation}.${tld}`,
                  variation,
                  tld,
                  available: false,
                  priceInCents: 0,
                  status: 'error',
                })
              )
            }
          })()
        )
      }
    }

    return Promise.allSettled(promises)
  }, [])

  const doSearch = useCallback(async () => {
    const name = searchName.trim()
    if (!name) {
      setError('Please enter a name')
      return
    }

    if (currentAbortController.current) {
      currentAbortController.current.abort()
    }

    currentAbortController.current = new AbortController()
    const signal = currentAbortController.current.signal

    setError('')
    setIsLoading(true)
    setPlatformResults(new Map())
    setDomainResults(new Map())

    try {
      await Promise.all([checkPlatforms(name, signal), checkDomains(name, signal)])
    } catch (err: any) {
      if (err.name !== 'AbortError' && !signal.aborted) {
        setError('Search failed. Please try again.')
      }
    } finally {
      if (!signal.aborted) {
        setIsLoading(false)
      }
    }
  }, [searchName, checkPlatforms, checkDomains])

  useEffect(() => {
    if (debounceTimer.current) {
      clearTimeout(debounceTimer.current)
    }

    if (searchName.trim()) {
      debounceTimer.current = setTimeout(() => {
        doSearch()
      }, 500)
    }

    return () => {
      if (debounceTimer.current) {
        clearTimeout(debounceTimer.current)
      }
    }
  }, [searchName])

  useEffect(() => {
    return () => {
      if (currentAbortController.current) {
        currentAbortController.current.abort()
      }
    }
  }, [])

  return (
    <div className="flex flex-col h-full px-6 py-3 gap-6">
      {/* Search Section */}
      <div className="text-center">
        <p className="text-muted mb-3">
          Find out if your project name is taken across platforms and domains
        </p>

        <div className="max-w-md mx-auto flex flex-col gap-3">
          <SearchField
            value={searchName}
            onChange={(val) => setSearchName(val.trim())}
            onSubmit={() => doSearch()}
            fullWidth
            variant="secondary"
            aria-label="Project name"
          >
            <SearchField.Group>
              <SearchField.SearchIcon />
              <SearchField.Input placeholder="Enter project name..." />
              <SearchField.ClearButton />
            </SearchField.Group>
          </SearchField>

          {error && (
            <Alert status="danger">
              <Alert.Indicator />
              <Alert.Content>
                <Alert.Description>{error}</Alert.Description>
              </Alert.Content>
            </Alert>
          )}
        </div>
      </div>

      {/* Results Section */}
      {searchName.trim() ? (
        <div className="space-y-6 flex-1 overflow-auto">
          <DomainAvailabilityMatrix
            domainResults={domainResults}
            isLoading={isLoading}
            searchName={searchName}
            onRetry={doSearch}
          />

          <PlatformAvailabilityCard
            platformResults={platformResults}
            isLoading={isLoading}
            onRetry={doSearch}
          />
        </div>
      ) : (
        <div className="flex items-center justify-center flex-1">
          <div className="text-center">
            <IconSearch className="text-4xl text-muted mx-auto mb-4" />
            <p className="text-muted">Enter a name above to check availability</p>
          </div>
        </div>
      )}
    </div>
  )
}

export default function NameChecker() {
  return (
    <NuqsAdapter>
      <NameCheckerContent />
    </NuqsAdapter>
  )
}
